### ISSUE TITLE
Nodejs server crashes with Redis instrumentation

### ISSUE THREAD

**Issue by shivahnshankar** [open-telemetry/opentelemetry-js-contrib#1057]
I am very new to this but i believe i am hitting a bug in the Redis implementation.
### What version of OpenTelemetry are you using?
0.24.0

### What version of Node are you using?
16.15

### What did you do?
App uses Redis 3.1.2 client and wanted to get traces but this error crashes the server:

/opt/nodeworkspace/test/node_modules/@opentelemetry/instrumentation-redis/build/src/instrumentation.js:39
if (instrumentation_1.isWrapped(moduleExports.RedisClient.prototype['internal_send_command'])) {
^

TypeError: Cannot read properties of undefined (reading 'prototype')
at InstrumentationNodeModuleDefinition.patch (/opt/nodeworkspace/test/node_modules/@opentelemetry/instrumentation-redis/build/src/instrumentation.js:39:75)
at RedisInstrumentation._onRequire (/opt/nodeworkspace/test/node_modules/@opentelemetry/instrumentation-redis/node_modules/@opentelemetry/instrumentation/build/src/platform/node/instrumentation.js:73:39)
at /opt/nodeworkspace/test/node_modules/@opentelemetry/instrumentation-redis/node_modules/@opentelemetry/instrumentation/build/src/platform/node/instrumentation.js:112:29

### What did you expect to see?
Server starts with no error

### What did you see instead?

Server is crashing with the above error

**Comment by shivahnshankar** [comment]
Used the latest version of Redis npm module and it worked fine. Closing this issue
