### ISSUE TITLE
@opentelemetry/instrumentation-aws-sdk does not instrument AWS SDK v3

### ISSUE THREAD

**Issue by ianwremmel** [open-telemetry/opentelemetry-js-contrib#1412]
### What version of OpenTelemetry are you using?

See package.json below

### What version of Node are you using?

18.x on AWS Lambda

### What did you do?

Upgraded from AWS SDK v2 to AWS SDK v3. 

### What did you expect to see?

I expected to see spans containing DynamoDB specific attributes.

### What did you see instead?

Just http details not, DynamoDB details.

### Additional context

This is very plausibly something I'm doing wrong, or something unexpected happening in a build step somewhere, but I'm at a loss on how to debug it further. Every Lambda uses the following build config:

```yml
    Metadata:
      BuildMethod: 'esbuild'
      BuildProperties:
        EntryPoints:
          - './index'
        External:
          - '@aws-sdk/*'
          - '@opentelemetry/api'
          - '@opentelemetry/exporter-trace-otlp-proto'
          - '@opentelemetry/resources'
          - '@opentelemetry/sdk-trace-base'
          - '@opentelemetry/sdk-trace-node'
        Minify: false
        Sourcemap: true
        Target: 'es2020'
```

### OpenTelemetry Setup Code

Even though the following code uses import/export, it's passed through the SAM CLI's ESBuild plugin and runs as CJS once deployed. 

```ts
import {assert} from '@code-like-a-carpenter/assert';
import {env} from '@code-like-a-carpenter/env';
import {diag} from '@opentelemetry/api';
import {
  CompositePropagator,
  W3CTraceContextPropagator,
} from '@opentelemetry/core';
import {OTLPTraceExporter} from '@opentelemetry/exporter-trace-otlp-proto';
import {AWSXRayPropagator} from '@opentelemetry/propagator-aws-xray';
import {B3InjectEncoding, B3Propagator} from '@opentelemetry/propagator-b3';
import {Resource} from '@opentelemetry/resources';
import type {SDKRegistrationConfig} from '@opentelemetry/sdk-trace-base';
import {BatchSpanProcessor} from '@opentelemetry/sdk-trace-base';
import type {
  NodeTracerConfig,
  NodeTracerProvider,
} from '@opentelemetry/sdk-trace-node';
import {SemanticResourceAttributes} from '@opentelemetry/semantic-conventions';
import {
  SentryPropagator,
  SentrySpanProcessor,
} from '@sentry/opentelemetry-node';

import {initSentry} from './sentry';

initSentry();

// Copied from
// https://github.com/open-telemetry/opentelemetry-lambda/blob/0a83149fe2f23a7dab64df6108cfa35f18cc2ae5/nodejs/packages/layer/src/wrapper.ts#L42-L50
declare global {
  function configureSdkRegistration(
    defaultSdkRegistration: SDKRegistrationConfig
  ): SDKRegistrationConfig;

  function configureTracerProvider(tracerProvider: NodeTracerProvider): void;

  function configureTracer(defaultConfig: NodeTracerConfig): NodeTracerConfig;
}

// In another file, there's a wrapper around each lambda which uses the globally attached tracerProvider to flush before exit. It would be lovely if OTel could provide a native solution for this.
declare global {
  // var seems to be the only typescript keyword that works here.
  // eslint-disable-next-line no-var
  var tracerProvider: NodeTracerProvider;
}

global.configureSdkRegistration = (config: SDKRegistrationConfig) => {
  return {
    ...config,
    propagator: new CompositePropagator({
      propagators: [
        new AWSXRayPropagator(),
        new W3CTraceContextPropagator(),
        new B3Propagator(),
        new B3Propagator({injectEncoding: B3InjectEncoding.MULTI_HEADER}),
        new SentryPropagator(),
      ],
    }),
  };
};

// we need to override the service name to avoid creating a new set of Honeycomb
// datasets every time a build runs in CI.
const serviceName = process.env.AWS_LAMBDA_FUNCTION_NAME?.split('-')
  ?.slice(-2, -1)
  ?.join('');

diag.info('Telemetry: included');

// This produces the config passed to new NodeTracerProvider()
const originalConfigureTracer = global.configureTracer;
global.configureTracer = ({resource, ...config}) => {
  diag.info('Telemetry: generating tracer config');

  assert(serviceName, 'Service name is required');
  const r = new Resource({
    [SemanticResourceAttributes.DEPLOYMENT_ENVIRONMENT]:
      process.env.STAGE_NAME ?? 'development',
    [SemanticResourceAttributes.FAAS_INSTANCE]:
      process.env.AWS_LAMBDA_LOG_STREAM_NAME ?? '',
    [SemanticResourceAttributes.FAAS_MAX_MEMORY]:
      process.env.AWS_LAMBDA_FUNCTION_MEMORY_SIZE ?? '',
    [SemanticResourceAttributes.SERVICE_NAME]: serviceName,
    [SemanticResourceAttributes.SERVICE_VERSION]: env('SHA'),
    'git.commit.sha': env('SHA'),
    'git.repository_url': env('REPOSITORY_URL'),
  });
  resource = resource ? resource.merge(r) : r;

  return originalConfigureTracer({
    ...config,
    resource,
  });
};

const originalConfigureTracerProvider = global.configureTracerProvider;
global.configureTracerProvider = (tracerProvider) => {
  diag.info('Telemetry: configureTracerProvider');

  // need to set tracerProvider so that we can flush at the end of each
  // invocation.
  diag.info('Telemetry: assigning global.tracerProvider');
  global.tracerProvider = tracerProvider;
  diag.info('Telemetry: assigned global.tracerProvider');

  // but since configureTracerProvider is defined, we need to repeat the default
  // behavior.
  diag.info('Telemetry: adding BatchSpanProcessor');
  tracerProvider.addSpanProcessor(
    new BatchSpanProcessor(new OTLPTraceExporter())
  );
  diag.info('Telemetry: added BatchSpanProcessor');

  diag.info('Telemetry: adding SentrySpanProcessor');
  tracerProvider.addSpanProcessor(new SentrySpanProcessor());
  diag.info('Telemetry: adding SentrySpanProcessor');

  if (originalConfigureTracerProvider) {
    diag.info('Telemetry: Running original configureTracerProvider');
    originalConfigureTracerProvider(tracerProvider);
    diag.info('Telemetry: Ran original configureTracerProvider');
  }
};
```

### Dependencies and Versions

```json
{
  "name": "@check-run-reporter/telemetry",
  "main": "src/index.ts",
  "dependencies": {
    "@code-like-a-carpenter/assert": "^1.0.0",
    "@code-like-a-carpenter/env": "^1.0.1",
    "@code-like-a-carpenter/telemetry": "^1.0.1",
    "@ianwremmel/data": "^3.1.0",
    "@octokit/request-error": "^2.1.0",
    "@opentelemetry/api": "~1.3.0",
    "@opentelemetry/core": "^1.9.1",
    "@opentelemetry/exporter-trace-otlp-proto": "0.34.0",
    "@opentelemetry/propagator-aws-xray": "^1.2.0",
    "@opentelemetry/propagator-b3": "^1.9.1",
    "@opentelemetry/resources": "1.8.0",
    "@opentelemetry/sdk-trace-base": "1.8.0",
    "@opentelemetry/sdk-trace-node": "1.8.0",
    "@opentelemetry/semantic-conventions": "1.8.0",
    "@sentry/opentelemetry-node": "^7.38.0",
    "@sentry/serverless": "^7.38.0"
  }
}
```

`@code-like-a-carpenter/telemetry` pulls in `"@opentelemetry/api": "1.4.0"` but is otherwise just convenience functions and shouldn't have anything to do with instrumentation.

Using ADOT version: `'arn:aws:lambda:${AWS::Region}:901920570463:layer:aws-otel-nodejs-amd64-ver-1-8-0:1'`

### Relevant Log Output

```
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.194000 Registering OpenTelemetry
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.204000 @opentelemetry/api: Registered a global for diag v1.3.0.
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 AwsLambdaDetector found resource. Resource {
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 attributes: {
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'cloud.provider': 'aws',
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'cloud.platform': 'aws_lambda',
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'cloud.region': 'us-east-1',
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'faas.name': 'check-run-reporter-FnRemixed-77xsc4EV6YYH',
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'faas.version': '16'
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 }
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 }
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 EnvDetector found resource. Resource {
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 attributes: { 'service.name': 'check-run-reporter-FnRemixed-77xsc4EV6YYH' }
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 }
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 ProcessDetector found resource. Resource {
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 attributes: {
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'process.pid': 17,
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'process.executable.name': '/var/lang/bin/node',
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'process.command': '/var/runtime/index.mjs',
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'process.command_line': '/var/lang/bin/node /var/runtime/index.mjs',
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'process.runtime.version': '18.12.1',
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'process.runtime.name': 'nodejs',
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 'process.runtime.description': 'Node.js'
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 }
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.209000 }
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.213000 Telemetry: generating tracer config
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.215000 Exporter "otlp" requested through environment variable is unavailable.
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.215000 Telemetry: configureTracerProvider
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.215000 Telemetry: assigning global.tracerProvider
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.216000 Telemetry: assigned global.tracerProvider
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.216000 Telemetry: adding BatchSpanProcessor
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.217000 Telemetry: added BatchSpanProcessor
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.217000 Telemetry: adding SentrySpanProcessor
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.217000 Telemetry: adding SentrySpanProcessor
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.219000 @opentelemetry/api: Registered a global for trace v1.3.0.
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.219000 @opentelemetry/api: Registered a global for context v1.3.0.
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.219000 @opentelemetry/api: Registered a global for propagation v1.3.0.
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.446000 (node:17) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.446000 Please migrate your code to use AWS SDK for JavaScript (v3).
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.446000 For more information, check the migration guide at https://a.co/7PzMCcy
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.446000 at emitWarning (/var/node_modules/aws-sdk/lib/maintenance_mode_message.js:21:13)
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.446000 at Timeout._onTimeout (/var/node_modules/aws-sdk/lib/maintenance_mode_message.js:29:5)
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.446000 at listOnTimeout (node:internal/timers:564:17)
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.446000 at processTimers (node:internal/timers:507:7)
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.482000 Applying patch for net module
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.494000 2023-02-26T17:43:01.494Z	undefined	DEBUG	@opentelemetry/instrumentation-http Applying patch for http@18.12.1
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.734000 2023-02-26T17:43:01.734Z	undefined	DEBUG	@opentelemetry/instrumentation-http Applying patch for https@18.12.1
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:01.842000 2023-02-26T17:43:01.842Z	undefined	DEBUG	aws-sdk instrumentation: applying patch to aws-sdk v3 client send
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.114000 2023-02-26T17:43:02.114Z	undefined	WARN	Failed extracting version /var/task
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.115000 2023-02-26T17:43:02.114Z	undefined	DEBUG	Applying patch for lambda handler
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.115000 2023-02-26T17:43:02.115Z	undefined	DEBUG	patch handler function
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.125000 EXTENSION	Name: collector	State: Ready	Events: [INVOKE,SHUTDOWN]
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.127000 START RequestId: 1dc72f59-d1b7-4077-aa6f-f5173ff86d5f Version: 16
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.180000 2023-02-26T17:43:02.180Z	1dc72f59-d1b7-4077-aa6f-f5173ff86d5f	DEBUG	@opentelemetry/instrumentation-http https instrumentation outgoingRequest
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.181000 2023-02-26T17:43:02.181Z	1dc72f59-d1b7-4077-aa6f-f5173ff86d5f	DEBUG	@opentelemetry/instrumentation-http http.ClientRequest return request
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.184000 2023-02-26T17:43:02.184Z	1dc72f59-d1b7-4077-aa6f-f5173ff86d5f	DEBUG	@opentelemetry/instrumentation-http https instrumentation outgoingRequest
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.185000 2023-02-26T17:43:02.185Z	1dc72f59-d1b7-4077-aa6f-f5173ff86d5f	DEBUG	@opentelemetry/instrumentation-http http.ClientRequest return request
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.187000 2023-02-26T17:43:02.187Z	1dc72f59-d1b7-4077-aa6f-f5173ff86d5f	DEBUG	@opentelemetry/instrumentation-http https instrumentation outgoingRequest
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.187000 2023-02-26T17:43:02.187Z	1dc72f59-d1b7-4077-aa6f-f5173ff86d5f	DEBUG	@opentelemetry/instrumentation-http http.ClientRequest return request
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.189000 2023-02-26T17:43:02.189Z	1dc72f59-d1b7-4077-aa6f-f5173ff86d5f	DEBUG	@opentelemetry/instrumentation-http https instrumentation outgoingRequest
2023/02/26/[16]6f9b07ad21a04050a200688aa5fa70c0 2023-02-26T17:43:02.189000 2023-02-26T17:43:02.189Z	1dc72f59-d1b7-4077-aa6f-f5173ff86d5f	DEBUG	@opentelemetry/instrumentation-http http.ClientRequest return request
```

The warning about SDK v2 is caused by `@sentry/serverless` pulling it in whether it's in use or not. When I removed Sentry, that warning went away, but the AWS instrumentation didn't work any better.

**Comment by ianwremmel** [comment]
I'm not sure what changed since this morning, but I now see properly instrumented DynamoDB spans but SQS spans still show up as plain HTTPS spans

**Comment by blumamir** [comment]
@ianwremmel The instrumentation is implemented and tested to support v3 for all services including SQS.

Can you please try to remove other instrumentation libraries and see if it makes any difference? I suspect that the sentry packages might be colliding with otel.

**Comment by blumamir** [comment]
Thanks for the update

Closing this issue since your setup is working now. Feel free to reopen if you have other issues in the future.
