### ISSUE TITLE
@opentelemetry/instrumentation crashes when used with typescript `esModuleInterop: true`

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [open-telemetry/opentelemetry-js-contrib#1438]
### What version of OpenTelemetry are you using?

```json
{
  "dependencies": {
    "@opentelemetry/auto-instrumentations-node": "^0.36.4",
    "@opentelemetry/exporter-trace-otlp-http": "^0.36.1",
    "@opentelemetry/instrumentation": "^0.36.1",
    "@opentelemetry/instrumentation-aws-lambda": "^0.35.0",
    "@opentelemetry/instrumentation-aws-sdk": "^0.34.0",
    "@opentelemetry/instrumentation-dns": "^0.31.2",
    "@opentelemetry/instrumentation-http": "^0.36.1",
    "@opentelemetry/resources": "^1.10.1",
    "@opentelemetry/sdk-node": "^0.36.1",
    "@opentelemetry/sdk-trace-base": "^1.10.1",
    "@opentelemetry/sdk-trace-node": "^1.10.1",
    "@opentelemetry/semantic-conventions": "^1.10.1"
  }
}
```

### What version of Node are you using?

18

### What did you do?

I recently started instrumenting my Node Lambda Functions with the OpenTelemetry JS SDK. We write them in TypeScript and transpile them using `esbuild`. We have typescript configured using `esModuleInterop: true`. During the build the following error is shown

```bash
▲ [WARNING] Calling "RequireInTheMiddle" will crash at run-time because it's an import namespace object, not a function [call-import-namespace]

    ../../.yarn/__virtual__/@opentelemetry-instrumentation-virtual-4be7f7a678/0/cache/@opentelemetry-instrumentation-npm-0.36.1-606efe6525-07401e23e0.zip/node_modules/@opentelemetry/instrumentation/build/esm/platform/node/RequireInTheMiddleSingleton.js:63:8:
      63 │         RequireInTheMiddle(
         ╵         ~~~~~~~~~~~~~~~~~~

  Consider changing "RequireInTheMiddle" to a default import instead:

    ../../.yarn/__virtual__/@opentelemetry-instrumentation-virtual-4be7f7a678/0/cache/@opentelemetry-instrumentation-npm-0.36.1-606efe6525-07401e23e0.zip/node_modules/@opentelemetry/instrumentation/build/esm/platform/node/RequireInTheMiddleSingleton.js:27:7:
      27 │ import * as RequireInTheMiddle from 'require-in-the-middle';
         │        ~~~~~~~~~~~~~~~~~~~~~~~
         ╵        RequireInTheMiddle
```

the build succeeds anyway. If I then invoke the function I get the following error in the logs:

```log
2023-03-27T16:46:22.383Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "TypeError",
    "errorMessage": "RequireInTheMiddle3 is not a function",
    "stack": [
        "TypeError: RequireInTheMiddle3 is not a function",
        "    at RequireInTheMiddleSingleton3._initialize (/var/task/index.js:53274:9)",
        "    at new RequireInTheMiddleSingleton3 (/var/task/index.js:53270:14)",
        "    at RequireInTheMiddleSingleton3.getInstance (/var/task/index.js:53317:91)",
        "    at new InstrumentationBase3 (/var/task/index.js:53386:75)",
        "    at new AwsInstrumentation2 (/var/task/index.js:55209:9)",
        "    at Object.<anonymous> (/var/task/index.js:82015:5)",
        "    at Module._compile (node:internal/modules/cjs/loader:1218:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1081:32)",
        "    at Module._load (node:internal/modules/cjs/loader:922:12)"
    ]
}
```

### What did you expect to see?

That the import works as expected without crashing.

### What did you see instead?

Build warnings and crashes.

### Additional context

[This StackOverflow answer](https://stackoverflow.com/a/49256285) suggests that the culprit is indeed `esModuleInterop: true`.

**Comment by matthias-pichler-warrify** [comment]
Will reopen in https://github.com/open-telemetry/opentelemetry-js
