### ISSUE TITLE
BatchSpanProcessor from sdk-trace-web/sdk-trace-base is calling a function only available in node

### ISSUE THREAD

**Issue by LuWang1983** [open-telemetry/opentelemetry-js-contrib#1633]
### What version of OpenTelemetry are you using?
"@opentelemetry/api": "^1.4.1",
"@opentelemetry/exporter-trace-otlp-http": "^0.41.1",
"@opentelemetry/instrumentation-xml-http-request": "^0.41.1",
"@opentelemetry/propagator-b3": "^1.15.1",
"@opentelemetry/sdk-trace-web": "^1.15.1",

### What version of Node are you using?
14

### What did you do?
Hi, while debugging a test failure in our application after instrumented frontend tracing, I accidentally discovered a bug either directly in Otel. If you look at the error stack provided below, it's calling `Tracer` and `Span` in `sdk-trace-base`, which then calls `BatchSpanProcessor` in `sdk-trace-base` (we use `BatchSpanProcessor` in our application and imported from `@opentelemetry/sdk-trace-web` (But it seems like `sdk-trace-web` imports `BatchSpanProcessor` from `sdk-trace-base` as well. And if you look at the last line of the stack, `BatchSpanProcessor` is calling a function `unrefTimer` in `@opentelemetry/core` which is a node module. This is the reason our test failed because it's running in a simulated dom environment that has no access to node.
If I switch `BatchSpanProcessor` to `SimpleSpanProcessor`, it doesn't run into this bug.
It's a weird bug. For now, I'm mocking the telemetry module to not run in our tests but the issue seems to come from `BatchSpanProcessor`.
```
    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "node" test environment.

    TypeError: timer.unref is not a function

      93 |       (span) => {
      94 |         const result = callback(span);
    > 95 |         span.end();
         |              ^
      96 |         return result;
      97 |       },
      98 |     );

      at unrefTimer (../../../node_modules/@opentelemetry/core/src/platform/node/timer-util.ts:17:9)
      at BatchSpanProcessor._maybeStartTimer (../../../node_modules/@opentelemetry/sdk-trace-base/src/export/BatchSpanProcessorBase.ts:229:15)
      at BatchSpanProcessor._addToBuffer (../../../node_modules/@opentelemetry/sdk-trace-base/src/export/BatchSpanProcessorBase.ts:139:10)
      at BatchSpanProcessor.onEnd (../../../node_modules/@opentelemetry/sdk-trace-base/src/export/BatchSpanProcessorBase.ts:97:10)
      at MultiSpanProcessor.onEnd (../../../node_modules/@opentelemetry/sdk-trace-base/src/MultiSpanProcessor.ts:58:21)
      at Span.end (../../../node_modules/@opentelemetry/sdk-trace-base/src/Span.ts:239:25)
      at ../../../lib/observability/browser/src/lib/browser-trace.ts:95:14
      at StackContextManager.with (../../../node_modules/@opentelemetry/sdk-trace-web/src/StackContextManager.ts:120:17)
      at ContextAPI.with (../../../node_modules/@opentelemetry/api/src/api/context.ts:77:42)
      at Tracer.startActiveSpan (../../../node_modules/@opentelemetry/sdk-trace-base/src/Tracer.ts:239:28)
      at getOrStartSpan (../../../lib/observability/browser/src/lib/browser-trace.ts:91:24)
      at createTracingAttributes (../../../lib/observability/browser/src/lib/browser-trace.ts:54:3)
      at handler (src/app/services/ingest-messaging.ts:67:7)
      at callTheUserObjectsOperation (../../../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (../../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (../../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at EventTargetImpl._dispatch (../../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at EventTargetImpl.dispatchEvent (../../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at dispatchEvent (../../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at src/app/components/Routes/NewVideo.spec.tsx:81:14
      at batchedUpdates$1 (../../../node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (../../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at Object.<anonymous> (src/app/components/Routes/NewVideo.spec.tsx:73:5)
```

**Comment by blumamir** [comment]
Thank you for reporting this.

Since the bug is in `@opentelemetry/sdk-trace-base` which is a core package, I will move the issue to the core repo
