### ISSUE TITLE
aws-sdk instrumentation - a "TypeError: _c.forEach is not a function" error is thrown for bad SQS.sendMessageBatch input

### ISSUE THREAD

**Issue by harelmo-lumigo** [open-telemetry/opentelemetry-js-contrib#1975]
### What version of OpenTelemetry are you using?
0.48.0

### What version of Node are you using?
v18.17.1

### What did you do?
I ran the following script:
```js
const { AwsInstrumentation } = require('@opentelemetry/instrumentation-aws-sdk');
const { registerInstrumentations } = require('@opentelemetry/instrumentation');
const AWS = require('aws-sdk');

registerInstrumentations({ instrumentations: [new AwsInstrumentation()] });

AWS.config.update({ region: 'us-west-2' });

const sqs = new AWS.SQS();

// A bad "Entries" object, should be an array
const Entries = { Key1: { MessageBody: 'This is the first message' } };

const params = {
  Entries,
  QueueUrl: "https://sqs.us-west-2.amazonaws.com/288057938227/harel-test-otel"
};

sqs.sendMessageBatch(params).promise().catch(console.error);
```

### What did you expect to see?
An validation error pointing out that `Entries` should have been an array

### What did you see instead?
The following error:
```bash
/my-folder/aws-sdk-bug-repro/node_modules/@opentelemetry/instrumentation-aws-sdk/build/src/services/sqs.js:39
                        (_c = (_b = request.commandInput) === null || _b === void 0 ? void 0 : _b.Entries) === null || _c === void 0 ? void 0 : _c.forEach((messageParams) => {
                                                                                                                                                   ^

TypeError: _c.forEach is not a function
    at SqsServiceExtension.requestPostSpanHook (/my-folder/aws-sdk-bug-repro/node_modules/@opentelemetry/instrumentation-aws-sdk/build/src/services/sqs.js:39:148)
    at ServicesExtensions.requestPostSpanHook (/my-folder/aws-sdk-bug-repro/node_modules/@opentelemetry/instrumentation-aws-sdk/build/src/services/ServicesExtensions.js:28:33)
    at /my-folder/aws-sdk-bug-repro/node_modules/@opentelemetry/instrumentation-aws-sdk/build/src/aws-sdk.js:344:41
    at NoopContextManager.with (/my-folder/aws-sdk-bug-repro/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
    at ContextAPI.with (/my-folder/aws-sdk-bug-repro/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at Request.promise (/my-folder/aws-sdk-bug-repro/node_modules/@opentelemetry/instrumentation-aws-sdk/build/src/aws-sdk.js:343:51)
    at Object.<anonymous> (/my-folder/aws-sdk-bug-repro/1.js:17:30)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
```

**Comment by pichlermarc** [comment]
Looks like we're iterating over it without checking if it's an array first. Might need some more defensive logic.
