### ISSUE TITLE
Unable to run compile or test

### ISSUE THREAD

**Issue by carlpett** [open-telemetry/opentelemetry-js-contrib#1986]
There seems to be omissions in the docs for getting from zero to working environment.

### What version of OpenTelemetry are you using?
`main`  / 2e9fce4d

### What version of Node are you using?
18.19

### What did you do?

Trying to follow CONTRIBUTING.md to get started in instrumentation-mongoose, but failing pretty much immediately. The below output is run in `plugins/node/instrumentation-mongoose`:

`npm run compile` reports a bunch of missing types in tests for the instrumentation.

```shell
$ npm test

> @opentelemetry/instrumentation-mongoose@0.35.0 test
> ts-mocha -p tsconfig.json --require '@opentelemetry/contrib-test-utils' 'test/**/*.test.ts'


/home/dev/src/github.com/open-telemetry/opentelemetry-js-contrib/node_modules/mocha/node_modules/yargs/lib/usage.js:240
      .concat(Object.keys(yargs.parsed.newAliases) || [])
                     ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.help (/home/dev/src/github.com/open-telemetry/opentelemetry-js-contrib/node_modules/mocha/node_modules/yargs/lib/usage.js:240:22)
    at Object.self.showHelp (/home/dev/src/github.com/open-telemetry/opentelemetry-js-contrib/node_modules/mocha/node_modules/yargs/lib/usage.js:432:15)
    at Array.<anonymous> (/home/dev/src/github.com/open-telemetry/opentelemetry-js-contrib/node_modules/mocha/lib/cli/cli.js:53:13)
    at Object.fail (/home/dev/src/github.com/open-telemetry/opentelemetry-js-contrib/node_modules/mocha/node_modules/yargs/lib/usage.js:41:17)
    at /home/dev/src/github.com/open-telemetry/opentelemetry-js-contrib/node_modules/mocha/node_modules/yargs/lib/command.js:246:36
npm ERR! Lifecycle script `test` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @opentelemetry/instrumentation-mongoose@0.35.0
npm ERR!   at location: /home/dev/src/github.com/open-telemetry/opentelemetry-js-contrib/plugins/node/instrumentation-mongoose
```

If I `npm test` from the root of the repo instead, I get three varieties of errors:
- Complaints about a missing version file, which is fixed by running the seemingly undocumented `npm run version:update`
- `Error: Cannot find module '/home/dev/src/github.com/open-telemetry/opentelemetry-js-contrib/node_modules/@opentelemetry/contrib-test-utils/build/src/index.js'. Please verify that the package.json has a valid "main" entry`
- The above mocha error for `lru-memoizer` and `amqplib`.

`npm run compile` in the root also results in a large number of errors.

I'm running a quite vanilla setup. Most unusal would be running on Linux, but I don't see anything apparent that would be OS-dependent?

### What did you expect to see?
Hopefully all green tests before I start breaking things

### What did you see instead?
See above

**Comment by JamieDanielson** [comment]
@carlpett sorry you're experiencing some of these problems with the monorepo setup. I know we've recently made some changes so that could be adding to the problems right now too.

When I work on something I typically do an `npm install` and `npm run compile` from the root and then the instrumentation I want to work on. So for example, if I wanted to make changes to that instrumentation I would go in this order:
- From root, `npm install`
- From root, `npm run compile`
- In plugins/node/instrumentation-mongoose, `npm install`
- In plugins/node/instrumentation-mongoose, `npm run compile`

Does this help? You are right, we do want to find a way to document this properly that is helpful for new users, and even not-so-new users because monorepo dev setup can be tough 😅

**Comment by JamieDanielson** [comment]
@carlpett I opened PR #2026 to update the Contributing doc a bit, hoping to help clear up confusion for folks running into the same sort of issues you have. I'd love to know if you have thoughts on it!

**Comment by carlpett** [comment]
Sorry for the lack of attention here, got sidetracked at work. I could've sworn I did those things you mention, since I said in the original report that I got errors when running compile in the root dir... But running it again now, it works :shrug: So I've successfully run the tests now!

I'll have a look at the PR!
