### ISSUE TITLE
mongodb: cannot load plugin

### ISSUE THREAD

**Issue by StefanCenusa** [open-telemetry/opentelemetry-js-contrib#361]
### What version of OpenTelemetry are you using?
0.17.0
0.13.1 - @opentelemetry/plugin-mongodb

### What version of Node are you using?
14.16.0

### What did you do?
Load the mongodb plugin
```
const provider: NodeTracerProvider = new NodeTracerProvider ({
    plugins: [{
        express: {
            enabled: true,
            path: '@opentelemetry/plugin-express',
        },
        http: {
            enabled: true,
            path: '@opentelemetry/plugin-http',
        },
        https: {
            enabled: true,
            path: '@opentelemetry/plugin-http',
        },
        mongodb: {
            enabled: true,
            path: '@opentelemetry/plugin-mongodb',
            enhancedDatabaseReporting: true
        }
    }]
});
```

### What did you expect to see?
mongodb plugin to work and see traces from my connection to mongodb server instance.

### What did you see instead?
I've added a breakpoint in `node_modules/@opentelemetry/plugin-mongodb/build/src/mongodb.js` at first line in `patch()` method. After the `this._logger.debug` function call, it throws, and PluginLoader catches the error.
```
TypeError: Cannot read property 'debug' of undefined
    at MongoDBPlugin.patch (/<REDACTED>/node_modules/@opentelemetry/plugin-mongodb/build/src/mongodb.js:39:20)
    at MongoDBPlugin.enable (/<REDACTED>/node_modules/@opentelemetry/plugin-mongodb/node_modules/@opentelemetry/core/src/platform/node/BasePlugin.ts:46:17)
    at /<REDACTED>/node_modules/@opentelemetry/instrumentation/src/platform/node/old/PluginLoader.ts:186:25
    at Module.Hook._require.Module.require (/<REDACTED>/node_modules/require-in-the-middle/index.js:154:32)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/<REDACTED>.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/<REDACTED>/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/<REDACTED>/node_modules/ts-node/src/index.ts:1059:12)
```

### Additional context
I've belive `api_1.diag` should be used instead of `this._logger` to work with latest opentelemetry versions.

**Comment by Flarna** [comment]
That's expected because OTel 0.17.x is not compatible to mongodb plugin 0.13.x. see https://github.com/open-telemetry/opentelemetry-js#compatibility-matrix

Work is ongoing to release a new version of plugins hosted here.

**Comment by StefanCenusa** [comment]
@Flarna Thank you for your quick reply. It seems I've missed the compatibility matrix.
