### ISSUE TITLE
MongoDB Instrumentation causes type error on command callback

### ISSUE THREAD

**Issue by jamesalucas** [open-telemetry/opentelemetry-js-contrib#402]
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
"@opentelemetry/instrumentation-mongodb": "0.14.0",
"@opentelemetry/instrumentation": "0.18.2",

### What version of Node are you using?
14.15.4

### What did you do?
Instrumented code using MongoDB, at runtime, after being up for a few seconds the app crashes at mongodb/lib/cmap/connection.js:277 as the callback it attempts to invoke is undefined.

### What did you expect to see?
No TypeError

### What did you see instead?
 TypeError: callback is not a function
     at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:277:5)
     at MessageStream.emit (events.js:315:20)
     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
     at writeOrBuffer (internal/streams/writable.js:358:12)
     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
     at Socket.ondata (internal/streams/readable.js:719:22)
     at Socket.emit (events.js:315:20)
     at addChunk (internal/streams/readable.js:309:12)
     at readableAddChunk (internal/streams/readable.js:284:9)
 [ERROR] 14:52:57 TypeError: callback is not a function

### Additional context

From debugging, the command being invoked is from `measureRoundTripTime`:

```
rttPinger[kConnection].command('admin.$cmd', { ismaster: 1 }, err => {
    if (err) {
      rttPinger[kConnection] = undefined;
      rttPinger[kRoundTripTime] = 0;
      return;
    }

    measureAndReschedule();
  });
```

The command is { ismaster:1 } and the callback follows, but it seems that the patching of the server command may be passing in the callback incorrectly?

If I change this:
```
if (!currentSpan ||
                    typeof resultHandler !== 'function' ||
                    typeof cmd !== 'object') {
                    return original.call(this, server, ns, cmd, typeof options === 'function' ? callback: options, callback);
                }
```
to:
```
if (!currentSpan ||
                    typeof resultHandler !== 'function' ||
                    typeof cmd !== 'object') {
                    return original.call(this, server, ns, cmd, options, callback);
                }
```

So that the original arguments make it through to the original call then the callback is defined and tracing appears to work as expected, but clearly I don't know what I'm doing and this may have broken something! :-)

**Comment by jamesalucas** [comment]
I'm using node-mongodb-native 3.6.3 with MongoDB 4.4 configured as a single node replica set. Is this supported? I saw the supported version was '>=3.3 <4' but assumed this was referring to the driver version rather than the DB version, but if it's the MongoDB version then I can see it wouldn't be supported. Thanks!

**Comment by vmarchaud** [comment]
It effectively reference the driver so thats weird, i just tested and the tests run fine with 3.6 so it might just not be covered by tests. Are you open to make a PR to fix this ?

**Comment by dobesv** [comment]
I am having the same issue for some reason:

```
TypeError: callback is not a function
    at MessageStream.messageHandler (/home/ubuntu/app/.yarn/$$virtual/mongodb-virtual-9a03103ae7/0/cache/mongodb-npm-3.6.5-df947000e5-6a838b79e1.zip/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/home/ubuntu/app/.yarn/$$virtual/mongodb-virtual-9a03103ae7/0/cache/mongodb-npm-3.6.5-df947000e5-6a838b79e1.zip/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/ubuntu/app/.yarn/$$virtual/mongodb-virtual-9a03103ae7/0/cache/mongodb-npm-3.6.5-df947000e5-6a838b79e1.zip/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

```

Could it be related to the use of sharding or replicasets?

**Comment by dobesv** [comment]
```
const resultHandler = typeof options === 'function' ? options : callback;
                if (!currentSpan ||
                    typeof resultHandler !== 'function' ||
                    typeof ops !== 'object') {
                    return original.call(this, server, ns, ops, typeof options === 'function' ? callback : options, callback);
                }
                const span = instrumentation.tracer.startSpan(`mongodb.${operationName}`, {
                    kind: api_1.SpanKind.CLIENT,
                });
                instrumentation._populateAttributes(span, ns, server, 
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                operationName !== 'insert' ? ops[0] : undefined);
                const patchedCallback = instrumentation._patchEnd(span, resultHandler);
                return original.call(this, server, ns, ops, typeof options === 'function' ? patchedCallback : options, patchedCallback);
```

Something about this logic does seem a bit strange.  On this line:

```
original.call(this, server, ns, ops, typeof options === 'function' ? callback : options, callback)
```

If `options` is a function, we pass `callback`.  However, if `options` is a function, `callback` is probably `undefined`, right?

It seems like the intention here is to just pass through the parameters, which would be achieved like this:

```
original.call(this, server, ns, ops, options, callback)
```

**Comment by dobesv** [comment]
I created this patchfile using `yarn patch` to work around the issue:

```
diff --git a/build/src/mongodb.js b/build/src/mongodb.js
index 1c6caf4abad0c17c82fab2e98f08b53cceef2041..bf8fb42dd77a631d6e9f1f37013ba6e3b36d2f2b 100644
--- a/build/src/mongodb.js
+++ b/build/src/mongodb.js
@@ -95,12 +95,12 @@ class MongoDBInstrumentation extends instrumentation_1.InstrumentationBase {
                 if (!currentSpan ||
                     typeof resultHandler !== 'function' ||
                     typeof ops !== 'object') {
-                    return original.call(this, server, ns, ops, typeof options === 'function' ? callback : options, callback);
+                    return original.call(this, server, ns, ops, options, callback);
                 }
                 const span = instrumentation.tracer.startSpan(`mongodb.${operationName}`, {
                     kind: api_1.SpanKind.CLIENT,
                 });
-                instrumentation._populateAttributes(span, ns, server,
+                instrumentation._populateAttributes(span, ns, server,
                 // eslint-disable-next-line @typescript-eslint/no-explicit-any
                 operationName !== 'insert' ? ops[0] : undefined);
                 const patchedCallback = instrumentation._patchEnd(span, resultHandler);
@@ -118,7 +118,7 @@ class MongoDBInstrumentation extends instrumentation_1.InstrumentationBase {
                 if (!currentSpan ||
                     typeof resultHandler !== 'function' ||
                     typeof cmd !== 'object') {
-                    return original.call(this, server, ns, cmd, typeof options === 'function' ? callback : options, callback);
+                    return original.call(this, server, ns, cmd, options, callback);
                 }
                 const commandType = instrumentation._getCommandType(cmd);
                 const type = commandType === types_1.MongodbCommandType.UNKNOWN ? 'command' : commandType;
@@ -141,7 +141,7 @@ class MongoDBInstrumentation extends instrumentation_1.InstrumentationBase {
                 if (!currentSpan ||
                     typeof resultHandler !== 'function' ||
                     typeof cmd !== 'object') {
-                    return original.call(this, server, ns, cmd, cursorState, typeof options === 'function' ? callback : options, callback);
+                    return original.call(this, server, ns, cmd, cursorState, options, callback);
                 }
                 const span = instrumentation.tracer.startSpan('mongodb.find', {
                     kind: api_1.SpanKind.CLIENT,
@@ -160,7 +160,7 @@ class MongoDBInstrumentation extends instrumentation_1.InstrumentationBase {
                 const currentSpan = api_1.getSpan(api_1.context.active());
                 const resultHandler = typeof options === 'function' ? options : callback;
                 if (!currentSpan || typeof resultHandler !== 'function') {
-                    return original.call(this, server, ns, cursorState, batchSize, typeof options === 'function' ? callback : options, callback);
+                    return original.call(this, server, ns, cursorState, batchSize, options, callback);
                 }
                 const span = instrumentation.tracer.startSpan('mongodb.getMore', {
                     kind: api_1.SpanKind.CLIENT,

```

**Comment by vmarchaud** [comment]
Will be released when the next release
