### ISSUE TITLE
express: unref is not a function on Node 8

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [open-telemetry/opentelemetry-js-contrib#78]
### What version of OpenTelemetry are you using?
`^0.8.3`

### What version of Node are you using?
`v8.17.0`

### What did you do?
Ran the demo in https://github.com/open-telemetry/opentelemetry-js/tree/master/getting-started/traced-example

### What did you see instead?
```
TypeError: setImmediate(...).unref is not a function
    at /home/src/opentelemetry-js/getting-started/traced-example/node_modules/@opentelemetry/plugin-express/build/src/express.js:159:20
    at Layer.handle [as handle_request] (/home/src/opentelemetry-js/getting-started/traced-example/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/src/opentelemetry-js/getting-started/traced-example/node_modules/express/lib/router/index.js:317:13)
    at /home/src/opentelemetry-js/getting-started/traced-example/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/src/opentelemetry-js/getting-started/traced-example/node_modules/express/lib/router/index.js:335:12)
    at next (/home/src/opentelemetry-js/getting-started/traced-example/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/src/opentelemetry-js/getting-started/traced-example/node_modules/express/lib/router/index.js:174:3)
    at Function.handle (/home/src/opentelemetry-js/getting-started/traced-example/node_modules/express/lib/application.js:174:10)
    at Server.app (/home/src/opentelemetry-js/getting-started/traced-example/node_modules/express/lib/express.js:39:9)
    at emitTwo (events.js:126:13)
```

### Additional context
`unref` was added in node 9.7.0 https://nodejs.org/docs/latest-v12.x/api/timers.html#timers_immediate_unref and can't be used on node 8

**Comment by dyladan** [comment]
We shouldn't need to unref the setImmediate anyways as it will only hold the process open for one cycle at worst. I'll look deeper into it and make sure it is safe to remove today.
